version: "3"

services:
  db:
    image: mongo
    container_name: 'urlshortener-mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js
      - ./mongoDB:/data/db

  app:
    container_name: 'urlshortener-app'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
          max-file: "3"
          max-size: "10m"
